name: Validate Code
on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: ./
          log_level: WARNING
          skip_git_check: false
      - name: Save HTML5 validation errors
        run: echo "${{ steps.html5validation.outputs.errors }}" > html5_errors.txt

      - name: Display HTML5 validation errors
        run: cat html5_errors.txt